### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by davideicardi** [melikpehlivanov/AuctionSystem#279]
For what I can see, mainly from the youtube video, this project looks very good. Thank you for sharing it!

I could be interested in support it. I have a potential customer that could invest some money and I can invest with my time for new features, bug fixing and documentation.

But I find a little bit difficult to understand the real status of the project.

Do you think it is "ready for production"? If not, what do you think is missing? (for sure we need a little bit more documentation ...)
Where data are stored? In Redis and Cloudinary only?

**Comment by melikpehlivanov** [comment]
Hello, @davideicardi.

First of all, I'd like to thank you for contacting me.

Now to your questions:

Currently, this application is in some kind of "beta" version. The application works fine but in my humble opinion it's really far away from being "production" app. There's literally tons of work and optimizations which should be made before this app going live. It really depends on what the traffic and usage there will be, but I'd say that this app isn't ready for production environment.

For data storage it's completely plug & play since it can work with many databases, however if I remember correctly, currently this app works with Mssql database. As I said above, there are many optimizations and changes that should be made before going "live". (Architectural, code refactoring, design, etc...)

If you're serious and would like to develop such application or use this one as for some kind of a start, please contact me by email at melikpehlivanov@gmail.com in order to discuss it further. :monkey_face:
